language: generic

services:
  - docker

env:
  global:
    - FILENAME='CV_Davide_Fauri'
  jobs:
    - LANGUAGE='italian' SHORTLANG='ita'
    - LANGUAGE='english' SHORTLANG='eng'

script:
  - cat $FILENAME.tex | sed 's|^\\usepackage\[[a-z,=]*\]{babel}|\\usepackage\['"$LANGUAGE"'\]{babel}|' > $FILENAME-$SHORTLANG.tex
  - ls -al *.tex
  - cat $FILENAME-$SHORTLANG.tex | grep babel
  - docker run --mount src=$TRAVIS_BUILD_DIR,dst=/usr/src/tex,type=bind dxjoke/tectonic-docker
    /bin/sh -c "tectonic --keep-intermediates --reruns 0 $FILENAME-$SHORTLANG.tex; biber $FILENAME-$SHORTLANG; tectonic --reruns 1 $FILENAME-$SHORTLANG.tex"

deploy:
  provider: releases
  edge: true
  api_key:
    secure: AAmoHOP8ivKVhhYAhzMJk/ipvm+tzFmCu1T++oeLEHSkln2oY8cuVxeux+5r7bgwqRIuDvyUoyMg0pgQU41avP4sAzvdZ5P8l6U112iU6oe59LyUTm1DYjfmdD6aCKFc1B56s9TJS+R2aAG1yQNV8dWGCXtxdQwaD/SYpx8AI+y+uS/gP7qBwN2Nd3PYxvcRYLV3D9Xja5NSdak2m1kjaohfs4TzhOiqU+60yEVRmcGt+M+36Dy8LMJO0zoHCN6iVF0+Qn/eROQVNBap1hhADha59fS5CEaZDWZCn/S0IN0Lbm70KhxOcb7BE7T78bX48WiFpZ8ThE48ovy9JO9hgIYgmpTAyOQHhLdzqfV04+Iyy4pSYEXsYe1bwcnGGxNqRu76Jt8DWawh55s26S9zDXDsBG7Qjvjj4+E8kQq8Qkw4OIFa7MpshfLjxW9M7WV2l/LMwOamDBsjF7nhq9XnE297NdSXpH/lvFOASwC9Aa7OZGhwtHt1V+lo5U+8DIEDqjZZGtWtidIKfrLQRjl7QwQxIKnkPMYz7sOHREs3+BSGJWrjogvSfO3y67ZKUw1gU7nD36jDk3g8QSpgWv0MgTRH6GG+OcfG23L1g3PxJgWjkeWNMXpXxWQ7JXxH66M7FhQjbGD/12CiIeFALgDZ62ieClfFl7zfPjpKlxFtbvM=
  file_glob: true
  file:
    - $FILENAME-$SHORTLANG.pdf
  on:
    tags: true
    all_branches: true
